"""Extract the bundled six-second probe into DDS frames for a limited cab test.

Only asset generation requires FFmpeg/ffprobe. Playback and packaging do not.
This precomputed frame sequence is not a live-video or YouTube texture bridge.
"""

from pathlib import Path
import argparse
import hashlib
import json
import shutil
import struct
import subprocess
import tempfile

MOD = Path(__file__).resolve().parents[1]
SOURCE = "assets/media/test.ogv"
DATA = "scripts/media/TMSCabinClipData.lua"
DIRECTORY = "assets/media/cabinTest"
SOURCE_WIDTH, SOURCE_HEIGHT, SOURCE_FPS = 640, 360, 30
# Store the complete image in a power-of-two texture. The monitor's full-range
# UVs and 16:9 geometry restore the source aspect; no padding or crop is needed.
WIDTH, HEIGHT, FPS, DURATION = 256, 256, 15, 6
MIP_COUNT = max(WIDTH, HEIGHT).bit_length()
FRAME_COUNT = FPS * DURATION
FRAME_NAMES = tuple(f"{DIRECTORY}/frame_{index:04d}.dds"
                    for index in range(1, FRAME_COUNT + 1))


def sha256(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def validate_dds(data, name):
    """Require the expected BC1 dimensions and every mip down to 1x1."""
    if len(data) < 128 or data[:4] != b"DDS " or data[84:88] != b"DXT1":
        raise ValueError(f"Invalid BC1 DDS frame: {name}")
    header = struct.unpack("<31I", data[4:128])
    if any(value <= 0 or value & (value - 1) for value in (header[2], header[3])):
        raise ValueError(f"DDS dimensions must be powers of two: {name}")
    if (header[0], header[2], header[3], header[6]) != (124, HEIGHT, WIDTH, MIP_COUNT):
        raise ValueError(f"Unexpected DDS dimensions or mip count: {name}")
    width, height, size = WIDTH, HEIGHT, 128
    for _ in range(header[6]):
        size += ((width + 3) // 4) * ((height + 3) // 4) * 8
        width, height = max(1, width // 2), max(1, height // 2)
    if len(data) != size:
        raise ValueError(f"Truncated or oversized DDS frame: {name}")


def frame_digest(mod):
    aggregate = hashlib.sha256()
    for name in FRAME_NAMES:
        data = (mod / name).read_bytes()
        validate_dds(data, name)
        aggregate.update(hashlib.sha256(data).digest())
    return aggregate.hexdigest()


def render_data(source_hash, frames_hash):
    lines = [
        "-- Generated by tools/generate_cabin_clip.py from the bundled test.ogv.",
        "-- Precomputed six-second test frames; not a live video/YouTube bridge.",
        "TMSCabinClipData = {",
        f'    sourceFile = "{SOURCE}",',
        f'    sourceSha256 = "{source_hash}",',
        f'    framesSha256 = "{frames_hash}",',
        f"    width = {WIDTH},",
        f"    height = {HEIGHT},",
        f"    sourceWidth = {SOURCE_WIDTH},",
        f"    sourceHeight = {SOURCE_HEIGHT},",
        f"    fps = {FPS},",
        f"    frameCount = {FRAME_COUNT},",
        f"    duration = {DURATION},",
        "    frames = {",
    ]
    lines.extend(f'        "{name}",' for name in FRAME_NAMES)
    lines.extend(["    }", "}", ""])
    return "\n".join(lines)


def validate_assets(mod=MOD):
    """Build-time source/data/frame integrity check, requiring only stdlib."""
    mod = Path(mod).resolve()
    expected = {Path(name).name for name in FRAME_NAMES}
    actual = {path.name for path in (mod / DIRECTORY).glob("*.dds")}
    if actual != expected:
        raise ValueError("Cab test frames are incomplete or stale; run generate_cabin_clip.py")
    names = (SOURCE, DATA, *FRAME_NAMES)
    for name in names:
        path = mod / name
        if not path.is_file() or path.is_symlink() or not path.resolve().is_relative_to(mod):
            raise ValueError(f"Missing or unsafe cab clip asset: {name}")
    expected_data = render_data(sha256(mod / SOURCE), frame_digest(mod))
    if (mod / DATA).read_text(encoding="utf-8") != expected_data:
        raise ValueError("Cab clip source, frames or Lua metadata changed; run generate_cabin_clip.py")
    return list(FRAME_NAMES)


def probe_source(ffprobe, source):
    command = [ffprobe, "-v", "error", "-select_streams", "v:0",
               "-show_entries", "stream=width,height,r_frame_rate,duration",
               "-show_entries", "format=duration", "-of", "json", str(source)]
    result = json.loads(subprocess.run(command, check=True, capture_output=True,
                                       text=True).stdout)
    stream = result["streams"][0]
    duration = float(stream.get("duration", result["format"]["duration"]))
    if (stream["width"], stream["height"], stream["r_frame_rate"]) != (
            SOURCE_WIDTH, SOURCE_HEIGHT, f"{SOURCE_FPS}/1"):
        raise ValueError("Expected the bundled 640x360, 30fps test.ogv")
    if abs(duration - DURATION) > 0.001:
        raise ValueError("Expected the bundled six-second test.ogv")
    return stream


def generate(ffmpeg, ffprobe):
    from generate_monitor import write_dds

    source = MOD / SOURCE
    stream = probe_source(ffprobe, source)
    # Explicit sampling keeps source frame 0, 2, 4 ... at times 0, 1/15, 2/15 ...
    # instead of shifting the sequence by one source frame during fps rounding.
    command = [ffmpeg, "-hide_banner", "-loglevel", "error", "-threads", "1",
               "-i", str(source), "-an", "-sn", "-dn", "-t", str(DURATION),
               "-vf", f"select=not(mod(n\\,2)),scale={WIDTH}:{HEIGHT}:flags=lanczos",
               "-fps_mode", "passthrough", "-frames:v", str(FRAME_COUNT),
               "-pix_fmt", "rgb24", "-f", "rawvideo", "pipe:1"]
    raw = subprocess.run(command, check=True, capture_output=True).stdout
    frame_size = WIDTH * HEIGHT * 3
    if len(raw) != frame_size * FRAME_COUNT:
        raise ValueError(f"Expected {FRAME_COUNT} complete frames, received {len(raw)} bytes")
    destination = MOD / DIRECTORY
    destination.mkdir(parents=True, exist_ok=True)
    # Stage only our known output files. Unrelated files are never removed.
    with tempfile.TemporaryDirectory(prefix="tms_cabin_frames_") as staging_name:
        staging = Path(staging_name)
        aggregate = hashlib.sha256()
        for index, name in enumerate(FRAME_NAMES):
            frame = memoryview(raw)[index * frame_size:(index + 1) * frame_size]
            output = staging / Path(name).name
            write_dds(output, WIDTH, HEIGHT,
                      lambda x, y: tuple(frame[(y * WIDTH + x) * 3:(y * WIDTH + x) * 3 + 3]))
            data = output.read_bytes()
            validate_dds(data, name)
            aggregate.update(hashlib.sha256(data).digest())
        metadata = render_data(sha256(source), aggregate.hexdigest())
        for name in FRAME_NAMES:
            shutil.copyfile(staging / Path(name).name, MOD / name)
        (MOD / DATA).write_text(metadata, encoding="utf-8", newline="\n")
    validate_assets()
    total = sum((MOD / name).stat().st_size for name in FRAME_NAMES)
    print(f"Source: {SOURCE}, {stream['width']}x{stream['height']}, 30fps, {DURATION}s")
    print(f"Generated {FRAME_COUNT} BC1 frames: {WIDTH}x{HEIGHT}, {FPS}fps, {total} bytes with mipmaps")
    print(f"SHA256 source: {sha256(source)}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ffmpeg", default=shutil.which("ffmpeg"))
    parser.add_argument("--ffprobe", help="Defaults to ffprobe beside ffmpeg or on PATH")
    parser.add_argument("--check", action="store_true", help="Validate existing assets without FFmpeg")
    args = parser.parse_args()
    if args.check:
        validate_assets()
        print(f"Cab clip assets valid: {FRAME_COUNT} frames, source/data hashes match")
        return
    if not args.ffmpeg:
        parser.error("FFmpeg not found; pass --ffmpeg /path/to/ffmpeg")
    sibling = Path(args.ffmpeg).with_name("ffprobe" + Path(args.ffmpeg).suffix)
    ffprobe = args.ffprobe or (str(sibling) if sibling.is_file() else shutil.which("ffprobe"))
    if not ffprobe:
        parser.error("ffprobe not found; pass --ffprobe /path/to/ffprobe")
    generate(args.ffmpeg, ffprobe)


if __name__ == "__main__":
    main()
